(function() {function ba(){var b=window.parent,c,f;try{(function(){var b=null,d=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(b in d)if(d[b]in document){c=d[b];break}})(),f="undefined"!==typeof b.document[c]?function(){return!b.document[c]}:this.sd!=this.td.CrossDomain&&b.top.document.hasFocus?function(){return b.top.document.hasFocus()}:function(){return!0}}catch(g){f=function(){return!0}}this.ua=f}function ca(){return new ba}"use strict";window.a=window.a||{};
window.a.video=window.a.video||{};
window.a.video.K=function(){this.ed=function(){return function(){this.autoPlayIndicator=this.interval=this.technique=this.jb=this.audioVolume=this.error=this.viewabilityState=this.focus=this.$=this.objRight=this.objLeft=this.objBottom=this.objTop=this.clientHeight=this.clientWidth=this.id="";this.b=function(b){this.id=b.id;this.clientWidth=b.clientWidth;this.clientHeight=b.clientHeight;this.objTop=b.objTop;this.objBottom=b.objBottom;this.objLeft=b.objLeft;this.objRight=b.objRight;var c;c=b.percentViewable;
if("unmeasurable"===b.beaconViewabilityState)c=0;else if(b.technique&&"beacon"===b.technique)if("viewable"===b.beaconViewabilityState||"viewable"===b.viewabilityState){c=b.beacons;var f=0;if("viewable"==b.viewabilityState)for(var g=1;g<c.length;g++)if(c[g])f=100;else{f=50;break}c=f}else c=0;this.$=c;this.focus=b.focus;this.viewabilityState=b.viewabilityState;this.error=b.error;this.audioVolume=isNaN(b.volume)?null:b.volume;this.jb="fullScreen"==b.displayState||"fullScreenInteractive"==b.displayState;
this.technique=b.technique;this.interval=b.interval;this.autoPlayIndicator=b.autoPlayIndicator;return this}}}();this.dd=function(){return function(){this.s=this.u=this.L=this.wb=this.Ja=this.Ta=this.Xa=this.gc=this.hc=this.q4EndedMs=this.q3EndedMs=this.q2EndedMs=this.q1EndedMs=this.S=this.R=this.gb=this.yb=this.Ra=this.tc=this.va=this.uc=this.qb=this.ab=this.h=this.P=this.ib=this.l=this.i=this.Qa=this.Pa=this.Ab=this.Bb=this.Ka=this.B=this.w=this.M=this.v=this.Z=this.O=this.fa=this.ea="";this.Ia=
0;this.rb=this.sb=this.q4iabvms=this.q3iabvms=this.q2iabvms=this.q1iabvms=this.X=this.$a=this.ha=this.Cb=this.Za=this.qc=this.bb=this.ga=this.ca=this.W=this.Cc=this.F=this.m="";this.Ya=0;this.xb=function(b,c){""===this.m&&(this.m={});this.m[b]=c}}}();this.o={$c:1,Ic:2,sc:4,Hc:8,wc:16,Vb:32,Ub:64,Sb:128};this.fb=function(b){switch(b){case "Can not find $ovv":return this.o.Ic;case "ExternalInterface not available":return this.o.sc;case "Object not found":return this.o.Hc;case "Failed to determine viewport":return this.o.wc;
case "Ad in iFrame":return this.o.Vb;case "adID does not exist":return this.o.Ub;case "Wrong settings":return this.o.Sb}return this.o.$c};this.j=function(){function b(){this.isq4ms=this.isq3ms=this.isq2ms=this.isq1ms=this.vit=this.dvp_vaisfcs=this.dvp_tch=this.dvp_isfcs=this.tstype=this.vjsver=this.dvp_olc=this.dvp_vidNmms=this.dvp_openVVBuildVersion=this.dvp_openVVVersion=this.dvp_vidMinorVersion=this.avmax=this.avmin=this.isavmms=this.admutems=this.adexpms=this.adskippblems=this.narme=this.napr=
this.strp=""}b.prototype.b=function(c){this.strp=c.v;this.napr=c.M;this.narme=c.w;this.adskippblems=c.B;this.adexpms=c.R;this.admutems=c.S;this.isavmms=c.L;this.avmin=c.u;this.avmax=c.s;this.dvp_vidMinorVersion=c.fa;this.dvp_openVVVersion=c.O;this.dvp_openVVBuildVersion=c.Z;this.dvp_vidNmms=c.dvp_vidNmms=c.m&&c.m.dvp_vidNmms?c.m.dvp_vidNmms:"";this.dvp_olc=c.F;this.vjsver=c.ea;this.tstype=c.P;this.dvp_isfcs=c.W;this.dvp_tch=c.ca;this.dvp_vaisfcs=c.ga;this.vit=c.ha;this.isq1ms=c.q1EndedMs;this.isq2ms=
c.q2EndedMs;this.isq3ms=c.q3EndedMs;this.isq4ms=c.q4EndedMs;return this};return b}();this.Mc=function(b){return function(){b.prototype.constructor.call(this);this.b=function(c,f){b.prototype.b.call(this,c);this[f+"b0"]=c.ja;this[f+"b1"]=c.ka;this[f+"b2"]=c.la;this[f+"b3"]=c.ma;this[f+"b4"]=c.na;this[f+"b5"]=c.oa;this[f+"napt"]=c.wa;this[f+"vpend"]=c.cd;this["is"+f+"ms"]=c.rc;this[f+"ad"]=c.ac;this[f+"iabvms"]=c.Hb;this[f+"ps"]=c.aa;"q4"==f&&(this.qcmpiabva=c.X);return this}}}(this.j);this.Fc=function(b){return function(){b.prototype.constructor.call(this);
this.dvp_apv=this.dvp_ovvUsed=this.vct=this.dvp_ismms=this.isgmmims=this.isumms=this.isbxdmms=this.isbxdms=this.isvidinsmems=this.isfmms=this.ismms=this.advisonl=this.adhgt=this.adwdth=this.adtovpy=this.adtovpx=this.vphgt=this.vpwdth="";this.b=function(c){b.prototype.b.call(this,c);this.vpwdth=c.Bb;this.vphgt=c.Ab;this.adtovpx=c.Pa;this.adtovpy=c.Qa;this.adwdth=c.i;this.adhgt=c.l;this.advisonl=c.ib;this.ismms=c.h;this.isfmms=c.ab;this.isvidinsmems=c.Ka;this.isbxdms=c.hc;this.isbxdmms=c.gc;this.isumms=
c.Ja;this.isgmmims=c.Cc;this.dvp_ismms=c.Za;this.vct=c.Cb;this.dvp_ovvUsed=c.$a;this.dvp_apv=c.Ya;return this}}}(this.j);this.pb=function(b){return function(){b.prototype.constructor.call(this);this.adhgt=this.adwdth=this.isvidinsmems=this.isfnmms=this.isnmms="";this.b=function(c){b.prototype.b.call(this,c);this.isnmms=c.qb;this.isfnmms=c.uc;this.isvidinsmems=c.Ka;this.adwdth=c.i;this.adhgt=c.l;return this}}}(this.j);this.Zb=function(b){return function(){b.prototype.constructor.call(this);this.isucms=
"";this.b=function(c){b.prototype.b.call(this,c);this.isucms=c.yb;return this}}}(this.j);this.Yb=function(b){return function(){b.prototype.constructor.call(this);this.isadskippedms="";this.b=function(c){b.prototype.b.call(this,c);this.isadskippedms=c.Ra;return this}}}(this.j);this.error=function(b){return function(){b.prototype.constructor.call(this);this.ishems="";this.b=function(c){b.prototype.b.call(this,c);this.ishems=c.gb;return this}}}(this.j);this.zc=function(){return function(){this.dvp_ismms=
this.dvp_isiabvms=this.dvp_ffovv=this.isumms=this.isuiabvms=this.isfmms=this.ismms=this.isfiabvms=this.isiabvms="";this.b=function(b){this.isiabvms=b.va;this.isfiabvms=b.tc;this.ismms=b.h;this.isfmms=b.ab;this.isuiabvms=b.wb;this.isumms=b.Ja;this.dvp_ffovv=b.bb;this.dvp_ismms=b.Za;this.dvp_isiabvms=b.qc;return this}}}();this.Nc=function(b){return function(){b.prototype.constructor.call(this);this.b=function(c,f){b.prototype.b.call(this,c);this.isiabvms=c.va;this.ismms=c.h;this[f+"iabvms"]=c.sb;return this}}}(this.j);
this.Lc=function(b){return function(){b.prototype.constructor.call(this);this.b=function(c,f){b.prototype.b.call(this,c);this[f+"ad"]=c.rb;return this}}}(this.j);this.pc=function(){return function(){this.ismms=this.iscvmvms="";this.b=function(b){this.iscvmvms=b.Xa;this.ismms=b.h;return this}}}();this.lc=function(){return function(){this.ismms="";this.b=function(b,c){this[c]=b.Wa;this.ismms=b.h;return this}}}();this.mc=function(){return function(){this.ismms="";this.b=function(b,c,f){this[f]=b.nc;
this.ismms=b.h;c&&(this[c]=b.Wa);return this}}}();this.cc=function(){return function(){this.ismms=this.isbvmvms="";this.b=function(b){this.isbvmvms=b.Ta;this.ismms=b.h;return this}}}();this.yc=function(b){var c="";switch(b){case "AdVideoFirstQuartile":c="q1";break;case "AdVideoMidpoint":c="q2";break;case "AdVideoThirdQuartile":c="q3";break;case "AdVideoComplete":c="q4"}return c};this.Qb={ld:0,Fb:1,Ma:2,jd:4,Ob:8,Pb:16,Db:32,Eb:64,kd:128,Ib:256,gd:512};this.Rb={Na:0,Jb:1,Gb:2,md:3,fd:4};this.H={Na:0,
Nb:1,Kb:2,Lb:3,Mb:4};this.Dc=function(b){var c=this.H.Na;0<b&&300>=b?c=this.H.Nb:300<b&&399>=b?c=this.H.Kb:399<b&&639>=b?c=this.H.Lb:639<b&&(c=this.H.Mb);return c};this.Ec=function(b){return{Uc:{adView:b.rq.av,Bc:b.rq.ic,Oa:b.rq.adp,I:b.rq.adc,hasVolume:b.rq.hv,kb:b.rq.lvav,Y:b.rq.mdc,aa:b.rq.ps},Ga:{ob:b.rp.mt,Kc:b.rp.pt,Gc:b.rp.mr,Jc:b.rp.pr,Sa:b.rp.bl}}}};window.a=window.a||{};window.a.zb=function(){};window.a=window.a||{};window.a.video=window.a.video||{};window.a.video.f=window.a.video.f||{};
window.a.video.f.ud=function(b){this.pa=null;this.a={};this.g=b;this.Ha=function(c){this.g=c};this.qa=function(c,b,g){if(this.g){g&&(this.a[c]=b);var d;c="<tr class='cellData1'><td>"+c+"</td>";for(d in b)b.hasOwnProperty(d)&&"function"!==typeof b[d]&&(g=isNaN(b[d])?"":b[d],c=null===this.pa||b[d]!==this.pa[d]?c+'<td class="cellData0 ">'+g+"</td>":c+"<td>"+g+"</td>");c+="</tr>";for(var k in this.a){c=c+"<tr class='cellData1'><td>"+k+"</td>";for(d in this.a[k])this.a[k].hasOwnProperty(d)&&"function"!==
typeof this.a[k][d]&&(g=isNaN(this.a[k][d])?"":this.a[k][d],c=c+"<td>"+g+"</td>");c+="</tr>"}d="<div class='bottomLeft'><table class='dvTable'><tr><th>Impression ID</th><th>0%     </th><th>1%-24% </th><th>25%-49%</th><th>50%-74%</th><th>75%-99%</th><th>100%   </th><th>N/A</th></tr>{TR_TD}<tfoot class='tfoot'><td colspan=14 height=15></td></tfoot></table></div>".replace("{TR_TD}",c);k=window.top.document.getElementById("dvBucketLogger");k||(k=window.top.document.createElement("div"),k.id="dvBucketLogger",
window.top.document.body.insertBefore(k,null));k.innerHTML=d;this.pa=b}};this.ra=function(c,b){if(this.g){var g;g="";for(var d in c)c.hasOwnProperty(d)&&"function"!==typeof c[d]&&(g=g+"<tr class='cellData1'><td>"+d+" </td><td>"+c[d]+"</td></tr>");g=("<div class='bottomRight'><table class = 'dvTable'> <caption>"+b+"</caption><tr> <th>Param name</th><th>Value</th> </tr>{TR_TD}<tfoot class='tfoot'><td colspan=14 height=15></td></tfoot></table > </div>").replace("{TR_TD}",g);d=window.top.document.getElementById("eventCallLog");
d||(d=window.top.document.createElement("div"),d.id="eventCallLog",window.top.document.body.insertBefore(d,null));d.innerHTML=g}};this.T=function(b){if(this.g){var f=document.getElementById("log");f&&(f.innerHTML=b+"<br>"+f.innerHTML)}}};window.a=window.a||{};
window.a.ec=function(){var b={U:6,sa:25},b=b||{U:6,sa:25},c=Array(b.U),f,g;this.Wc=function(d,f){var g;0>d?g=0:100<d?g=b.U-1:(g=Math.floor(d/b.sa),0<d%b.sa?g++:0<d&&g++);isNaN(c[g])&&(c[g]=0);c[g]+=f};this.cb=function(){return g};this.Vc=function(b,c){isNaN(g)&&(g=0);0<b&&(g=g+c)};this.eb=function(){var b={};b.ja=c[0]?c[0]:"";b.ka=c[1]?c[1]:"";b.la=c[2]?c[2]:"";b.ma=c[3]?c[3]:"";b.na=c[4]?c[4]:"";b.oa=c[5]?c[5]:"";b.wa=f?f:"";return b};this.clear=function(){c=Array(b.U);f=g=void 0};this.Xc=function(b){isNaN(f)&&
(f=0);f=f+b}};window.a=window.a||{};window.a.Wb=function(){this.xc=function(){var b=window,c;try{var f;for(f=0;10>f;f++)b=b.parent,c=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body}catch(g){}return c}};window.a=window.a||{};window.a.video=window.a.video||{};window.a.video.f=window.a.video.f||{};
window.a.video.f.console=function(b){this.a=b;this.g={lb:1,nb:2,mb:4};this.Ha=function(b){this.a=b};this.qa=function(b,f){if(this.a&&(this.a&this.g.lb)===this.g.lb){var g="",d;for(d in f)f.hasOwnProperty(d)&&"function"!==typeof f[d]&&(g=g+" |"+d+":"+(isNaN(f[d])?"":f[d]));console.log("Buckets for "+b+", "+g)}};this.ra=function(b,f){if(this.a&&(this.a&this.g.nb)===this.g.nb){var g=f+" call: ",d;for(d in b)b.hasOwnProperty(d)&&"function"!==typeof b[d]&&(g=g+" | "+d+":"+b[d]);console.log("Event data: "+
g)}};this.T=function(b){this.a&&(this.a&this.g.mb)===this.g.mb&&console.log("log entry: "+b)}};window.a.video.pd={La:1};
window.a.video.Ga=function(){function b(){this.La={Da:function(b,c){var d=(new n.Lc).b(b,c);f(d)},Fa:function(b,d){b.sb=c();var k=(new n.Nc).b(b,d);g("VideoQuartile$ViewableIAB".replace("$",d[1]));f(k)},ba:function(b){b.h=c();b.Ja=b.h;b=(new n.Fc).b(b);g("IABMeasuredImpression");k("VideoImpressionViewabilityMeasured");f(b)},Ba:function(b){var t=c();b.va=t;b.wb=t;b.h||this.ba(b);b=(new n.zc).b(b);f(b);d("Impression viewed",b);g("IABViewableImpression");k("VideoImpressionViewableIAB")},Ca:function(b){g("IABAdViewable"+
b+"Seconds")},Aa:function(b){b.qb=c();b=(new n.pb).b(b);f(b);g("IABNotMeasuredImpression")},tb:function(b){var d=c();b.Xa=d;k("VideoImpressionViewableCustom");g("CustomViewabilityViewable");b=(new n.pc).b(b);f(b)},za:function(b){var d=c();b.Ta=d;g("BrandVisibilityViewable");b=(new n.cc).b(b);f(b)},Sc:function(){},Ea:function(b,c){var g=(new n.Mc).b(b,c);f(g);d(b.eventName,g,b)},xa:function(b,d,w,m){m&&l||(m=c(),b.Wa=m,w&&(k(w),g(w)),d&&(b=(new n.lc).b(b,d),f(b)))},ya:function(b,d,w,m,A){A&&l||(A=
c(),b.nc=A,m&&(k(m),g(m)),b=(new n.mc).b(b,d,w),f(b))}}}function c(){return $dv.tags[m].getTimeDiff()}function f(b){if(!0!==$dv.tags[m].Zc){var c={},d;for(d in b)""!==b[d]&&null!==b[d]&&void 0!==b[d]&&(c[d]=b[d]);$dv.registerEventCall(m,c,0)}}function g(b){$dv&&b&&($dv.pubSub.publish(b,m),window&&$dv.pubSub.publish(b,window.$frmId))}function d(b,c,d){d&&x.qa(m,d);x.ra(c,b)}function k(b){if(q){var c=window.$ovv||parent.$ovv;if(c){var d=$dv.tags[$uid].adID||$dv.tags[$uid].adid,c=c.dvjscb[d];a:{for(var f=
parent.document.getElementsByTagName("embed"),g=0;g<f.length;g++)if(f[g][d]||f[g]["onJsReady"+d]){d=f[g];break a}f=parent.document.getElementsByTagName("object");for(g=0;g<f.length;g++)if(f[g][d]||f[g]["onJsReady"+d]){d=f[g];break a}d=void 0}if(d&&c)d[c](b)}if(c=window.$dvvideo||parent.$dvvideo){var d=$dv.tags[$uid].adID||$dv.tags[$uid].adid,c=c.assets,k;for(k in c)(g=c[k])&&g.id==d&&"function"===typeof g.executeCB&&g.executeCB(b)}}}var l,m,x,n,p,C,q;this.Ac=function(c){m=c.uid;x=c.f;n=c.K;q=c.ia;
C=new b;l=c.bgm;p=C.La};this.ub=function(b){b=(new n.j).b(b);f(b)};this.ba=function(b){p.ba(b)};this.Ba=function(b){p.Ba(b)};this.Ca=function(b){p.Ca(b)};this.Aa=function(b){p.Aa(b)};this.Sc=function(){};this.Qc=function(b){b.yb=c();b=(new n.Zb).b(b);f(b);d("Ad user close",b)};this.Pc=function(b){var g=c();b.B||(b.B=g);b.Ra=g;b=(new n.Yb).b(b);f(b);d("Ad skipped",b)};this.Rc=function(b){b.gb=c();b=(new n.error).b(b);f(b);x.ra(b,"Error")};this.Ea=function(b,c){p.Ea(b,c)};this.tb=function(b){p.tb(b)};
this.za=function(b){p.za(b)};this.Oc=function(b){b.Ka=c();g("VideoImpressionServed")};this.Fa=function(b,c){p.Fa(b,c)};this.Da=function(b,c){p.Da(b,c)};this.xa=function(b,c,d,f){p.xa(b,c,d,f)};this.ya=function(b,c,d,f,g){p.ya(b,c,d,f,g)}};window.a=window.a||{};window.a.video=window.a.video||{};
window.a.video.Va=function(b){this.$b=b.adView;this.Tb=b.hasVolume;this.G=function(){};this.C=function(){};this.N=function(){};this.da=function(){};this.V=function(){};this.J=function(b,f,g,d,k){this.da(b,f,g,d,k);this.V(d,k)};this.D=function(){}};window.a=window.a||{};window.a.video=window.a.video||{};
window.a.video.jc=function(b,c){"number"===typeof b.adView&&"number"===typeof b.adStart&&"number"===typeof b.adEnd&&"boolean"===typeof b.hasVolume&&(window.a.video.Va.call(this,b),this.adStart=b.adStart,this.adEnd=b.adEnd,this.A=0,this.ta=this.hb=!1,this.G=function(b){c.za(b);this.G=function(){}},this.da=function(b,c,d,k){this.A+=k;!this.hb&&this.A>=this.adStart&&(this.ta=this.hb=!0);this.A>=this.adStart&&this.A<=this.adEnd&&!(b&&c>=this.$b&&(!this.Tb||null==d.audioVolume||-1==d.audioVolume||0<d.audioVolume))&&
(this.ta=!1,this.da=function(){})},this.V=function(b,c){this.ta&&this.A>=this.adEnd&&this.G(c)},this.D=function(b,c){this.adEnd=this.A;this.V(b,c)})};window.a=window.a||{};window.a.video=window.a.video||{};
window.a.video.kc=function(b,c){function f(b){3E5<=b.i*b.l&&d.kb&&(d.adView=d.kb);f=function(){}}function g(b){d.Oa&&b.Ua&&(d.I=b.Ua*d.Oa,d.Y&&(d.I=Math.min(d.Y,d.I)),g=function(){})}var d=b.Uc,k=b.Ga;window.a.video.Va.call(this,b);var l=0;this.C=function(b){f(b);c.xa(b,k.ob,k.Gc,k.Sa)};this.G=function(b){c.ya(b,k.ob,k.Kc,k.Jc,k.Sa);this.G=function(){}};this.da=function(b,c,f,g,k){var q=!0;b||(q=!1);d.adView&&d.adView>c&&(q=!1);d.hasVolume&&0==f.audioVolume&&(q=!1);k.i&&k.l&&d.aa&&k.i*k.l<d.aa&&(q=
!1);q?l+=g:d.Bc&&(l=0)};this.V=function(b,c){g(c);(d.I&&l>=d.I||d.Y&&l>=d.Y)&&this.G(c)}};window.a=window.a||{};window.a.video=window.a.video||{};
window.a.video.vb=function(b){function c(b){b=(b||"").toString().toLowerCase();var c=y.Qb;switch(b){case "geometry":case "css_invisibility":case "dom_obscuring":return c.Fb;case "beacon":return $dv.CommonData.BrowserId===$dv.Enums.BrowserId.hd?c.Ma:c.Eb;case "iphone_override":return c.Ib;case "safeframegeom":return c.Ob;case "safeframeinviewperc":return c.Pb;case "amp_intersectionobserver":return c.Db;case "resourcebased":return c.Ma}}function f(b){var c;switch(e.P){case $dv.Enums.TrafficScenario.CrossDomain:c=
da.xc()}b&&(e.i=b.objRight-b.objLeft,e.l=b.objBottom-b.objTop);!c||e.i&&e.l||(e.i=c.clientWidth,e.l=c.clientHeight)}function g(b,d){f(d);e.Cb=c(d.technique);e.Bb=d.clientWidth;e.Ab=d.clientHeight;e.Pa=d.objLeft;e.Qa=d.objTop;e.ib=50<=e.v;ea(e);u.ba(e);R=!0;g=function(){}}function d(b,c){c&&(e.M=c,e.w|=y.fb(c));f();u.Aa(e);R=!0;d=function(){}}function k(b){try{e.M=b+(b.message?"; error.message: "+b.message:""),e.w|=y.fb(b),G<A&&(G++,u.Rc(e))}catch(c){$dv.registerEventCall($uid||-1,{napr:"Error trying to send error event. "+
c,narme:1,ishems:1},0)}}function l(b,c){var d=B.eb(),g=B.cb();B.clear();var h=y.yc(b);e[h+"Buckets"]=d;e[h+"AudibleDuration"]=g;e[h+"ViewPercentageAtEnd"]=n(c);e[h+"EndedMs"]=$dv.tags[e.uid].getTimeDiff();d=W;try{for(var k=h[1],m=e[h+"EndedMs"],g=1;g<k;g++)e["q"+g+"EndedMs"]||(e["q"+g+"EndedMs"]=parseInt((m-d)*g/k))}catch(l){}f(c);e[h+"PlayerSize"]=y.Dc(e.i);e[h+"IABViewedMs"]=K;try{!$dv||2!=$dv.CommonData.BrowserId&&3!=$dv.CommonData.BrowserId||(e.ca=JSON.stringify(L),e.W=JSON.stringify(M),e.ga=
JSON.stringify(N)),e.F=e.F?e.F+" "+O:O}catch(l){}O=0;u.Ea({uid:e.uid,ea:e.ea,fa:e.fa,O:e.O,Z:e.Z,P:e.P,v:e.v,w:e.w,B:e.B,R:e.R,S:e.S,cd:e[h+"ViewPercentageAtEnd"],rc:e[h+"EndedMs"],M:e.M,wa:e[h+"Buckets"].wa,ja:e[h+"Buckets"].ja,ka:e[h+"Buckets"].ka,la:e[h+"Buckets"].la,ma:e[h+"Buckets"].ma,na:e[h+"Buckets"].na,oa:e[h+"Buckets"].oa,aa:e[h+"PlayerSize"],ac:e[h+"AudibleDuration"],L:e.L,s:e.s,u:e.u,F:e.F,ca:e.ca,W:e.W,m:e.m,ga:e.ga,ha:e.ha,X:e.X,Hb:K,q1EndedMs:e.q1EndedMs,q2EndedMs:e.q2EndedMs,q3EndedMs:e.q3EndedMs,
q4EndedMs:e.q4EndedMs},h);S=!1;H=0;K=void 0;T=!1}function m(b,c){e.bb=c;X=!0;u.Ba(e);m=function(){}}function x(){0<z.length&&I>=1E3*z[0]&&(u.Ca(z[0]),z.shift(),0==z.length&&(x=function(){}))}function n(b){return b.jb?100:0==P.ua(b)?0:b.$}function p(){$dv.registerEventCall($uid,{dvp_adclk:1},0);p=function(){}}function C(b,c){c.subscribe(fa,b,function(b,f){try{void 0!=window&&null!=window&&window.dv_config&&window.dv_config.debug?E.Ha(window.dv_config.debug):E.Ha(0);parent&&parent.DVViewableDetect&&
parent.DVViewableDetect(f.eventName,f.ovvArgs);var h=(new y.ed).b(f.ovvArgs.ovvData);h.interval=h.interval||c.interval||200;h.rd=$dv.CommonData.Scenario;var r=f.eventName,D=h.interval;E.T("Received event: "+r);switch(r){case "OVVLog":try{O++;var q=h.technique,v=h.focus;L[q]=L[q]?L[q]+1:1;M[v]=M[v]?M[v]+1:1;var U=Y.ua();N[U]=N[U]?N[U]+1:1}catch(A){}var Q=$dv.tags[e.uid].getTimeDiff();if(!Z||V)E.T("Ignore interval data.");else{var z,r=!0;null===h||h.error||null===h.$?r=!1:"unmeasurable"===h.viewabilityState&&
(J++,r=!1);r||e.xb("dvp_vidNap",h.$);z=r;var C="not_ready"!=h.viewabilityState,r=null;if(!z)(0==J||1<J)&&B.Xc(D);else if(C){if(null===e.v||""===e.v)e.v=n(h);r=n(h);B.Wc(r,D);E.T("setBucket: "+r+"%");e.Ia+=D;if(null!==h.audioVolume&&0<=h.audioVolume){B.Vc(h.audioVolume,D);e.L=e.L||Q;h.audioVolume=Math.ceil(100*h.audioVolume);""===e.u||""===e.s?(e.u=h.audioVolume,e.s=h.audioVolume):(e.u=Math.min(e.u,h.audioVolume),e.s=Math.max(e.s,h.audioVolume));var F=B.cb();!T&&200<=F&&(e.rb=F,u.Da(e,w),T=!0)}50<=
r?(I+=h.interval,H+=h.interval):H=I=0;!X&&2E3<=I&&m(h,0);0==S&&2E3<=H&&(K=$dv.tags[e.uid].getTimeDiff(),u.Fa(e,w),S=!0);ga(C,r,h,D,e);x(D)}!R&&C&&(z?g(Q,h):(0==J||1<J)&&d(Q,h.error));E.qa(e.uid,B.eb())}break;case "OVVImpression":m(h,1);break;case "OVVImpressionUnmeasurable":var G=$dv.tags[e.uid].getTimeDiff();e.xb("dvp_vidNmms",G);d(G,h.pb);break;case "AdImpression":W=$dv.tags[$uid].getTimeDiff();Z=!0;e.Ya=0<h.autoPlayIndicator?h.autoPlayIndicator:null;u.Oc(e);break;case "AdVideoMidpoint":w="q3";
e.Ua=2*e.Ia;l(r,h);break;case "AdVideoFirstQuartile":w="q2";l(r,h);break;case "AdVideoThirdQuartile":w="q4";l(r,h);break;case "AdVideoComplete":50<=n(h)&&(!(null!==h.audioVolume&&0<=h.audioVolume)||0<h.audioVolume)&&(e.X=$dv.tags[e.uid].getTimeDiff());l(r,h);ha(D,e);break;case "AdExpandedChange":e.R=$dv.tags[e.uid].getTimeDiff();break;case "AdSkippableStateChange":e.B=$dv.tags[e.uid].getTimeDiff();break;case "AdSkipped":u.Pc(e);break;case "AdUserClose":u.Qc(e);break;case "AdVolumeChange":0==h.audioVolume&&
(e.S=$dv.tags[e.uid].getTimeDiff());break;case "AdPaused":V=!0;break;case "AdPlaying":V=!1;break;case "AdStopped":$dv.tags[e.uid].Zc=!0;break;case "AdClickThru":p()}}catch(A){try{k(A)}catch(P){t.debug&&console.log("ovv event error: "+P)}}},!0)}function q(b){var c=!0;"undefined"!=typeof $dv.tags[b].AVO&&"undefined"!=typeof $dv.tags[b].AVO.fcs&&(c=!$dv.tags[$uid].AVO.fcs);P=c?Y:{ua:function(b){return b.focus}}}var W=0,t=b.Yc,w="q1",G=0,A=t?t.od||10:10,B=b.fc,da=b.Xb,y=b.K,ia=b.ad,e=new y.dd,E=b.f,u=
b.Tc,Z=!1,V=!1,R=!1,J=0,O=0,L={},M={},N={},I=0,S=!1,T=!1,H=0,K,X=!1,Y=b.dc,P,F,v,fa="OVVLog OVVImpression OVVImpressionUnmeasurable AdSkippableStateChange AdSkipped AdUserClose AdStarted AdImpression AdVideoStart AdStopped AdVideoFirstQuartile AdVideoMidpoint AdVideoThirdQuartile AdVideoComplete AdExpandedChange AdPaused AdPlaying AdVolumeChange AdClickThru".split(" "),z=[5,10,15],aa=1;this.start=function(){try{var b=function(){try{var c=5<=aa;a:{var d=F,g=null;try{if(window.$dvvideo||parent.$dvvideo){g=
window.$dvvideo||parent.$dvvideo;if(window.$ovv||parent.$ovv)g.buildVersion=window.$ovv?window.$ovv.releaseVersion||window.$ovv.version:parent.$ovv.releaseVersion||parent.$ovv.version,e.$a="1";var f=g.assets,m;for(m in f){var l=f[m];if(l&&l.id==d&&null!=l.player){v=g;break a}}}if(c&&(window.$ovv||parent.$ovv)){v=g=window.$ovv||parent.$ovv;break a}}catch(n){}v=void 0}if(v){e.O=v.releaseVersion||v.version;var p=e.O,p=(p||"").toString().toLowerCase(),q=y.Rb;e.ha="html5"===p?q.Gb:q.Jb;e.Z=v.buildVersion;
u.ub(e);t.irtf&&(e.irtf=t.irtf,ja(e));C(F,v)}else{if(c)throw"Can not find $ovv";aa++;setTimeout(b,500)}}catch(n){k(n)}};u.Ac({K:y,zb:ia,uid:$uid,nd:t.irtf,qd:t.rpv,bgm:t.bgm,ia:t.ia,f:E});e.ea=69;e.fa=0;e.uid=t?t.uid||$uid:$uid;e.P=$dv.CommonData.Scenario;F=t.adID||$dv.tags[e.uid].adID||$dv.tags[e.uid].adid;if(!F)throw"adID does not exist";q(e.uid);u.ub(e);b()}catch(c){k(c)}};var ga=b.c&&b.c.J&&"function"===typeof b.c.J?b.c.J:function(){},ea=b.c&&b.c.C&&"function"===typeof b.c.C?b.c.C:function(){},
ja=b.c&&b.c.N&&"function"===typeof b.c.N?b.c.N:function(){},ha=b.c&&b.c.D&&"function"===typeof b.c.D?b.c.D:function(){}};window.a=window.a||{};window.a.video=window.a.video||{};window.a.video.oc=function(b){this.bc=window.a.video.vb;var c=b.bd,f=c.length;b.c=b.c||{};b.c.J=function(b,d,k,l,m){for(var x=0;x<f;x++)c[x].J(b,d,k,l,m)};b.c.C=function(b){for(var d=0;d<f;d++)c[d].C(b)};b.c.N=function(b){for(var d=0;d<f;d++)c[d].N(b)};b.c.D=function(b,d){for(var k=0;k<f;k++)c[k].D(b,d)};this.bc(b)};
window.a=window.a||{};window.a.video=window.a.video||{};
try{videoCallback(function(b){b.rpv=$dv.tags[$uid].AVO?$dv.tags[$uid].AVO.rpv:b.rpv;b.ia=$dv.tags[$uid].AVO?$dv.tags[$uid].AVO.ajscb:void 0;b.bgm=$dv.tags[$uid].bgm||b.bgm;var c=void 0!=window&&null!=window&&window.dv_config&&window.dv_config.f?window.dv_config.f:new window.a.video.f.console(b?b.debug:0),f=new window.a.video.Ga,g=new window.a.video.K,d,k=[];d=$dv.tags[$uid].vc||b.vc||[];for(var l in d)d.hasOwnProperty(l)&&k.push(new window.a.video.kc(g.Ec(d[l]),f));if(d=$dv.tags[$uid].videoBrandVisibilty||
b.videoBrandVisibilty)d=new window.a.video.jc(d,f),void 0!=d&&k.push(d);d=window.a.video.vb;0<k.length&&(d=window.a.video.oc);(new d({Yc:b,bd:k,dc:new ca,fc:new window.a.ec,Xb:new window.a.Wb,K:g,ad:new window.a.zb,f:c,Tc:f})).start()})}catch(b){$dv.registerEventCall($uid||-1,{napr:"Error while staring video tag. "+b,narme:1,ishems:1},0)};})();
