(function(){function p(a,b){function c(a){k=!0;"undefined"!==typeof m&&clearTimeout(m);if("string"===typeof a)return"function"===typeof f&&f(a),!0;if("object"===typeof a||"undefined"===typeof a)return"object"===typeof a&&"error"===a.type?"function"===typeof f&&f(a):"function"===typeof l&&l(),!0}function d(){_poll(function(){return k}).setDelay(50).setMaxAttempts(g).setFailCallback(function(){debug.warn("Polling for script loader failed. src: "+a);c("Load Timeout Error")}).start()}var l=b,g=200,h=
!1,f,m,e=document.createElement("script"),n=document.getElementsByTagName("script")[0],k=!1;e.src=a;e.setAttribute("type","text/javascript");e.onload=e.onerror=e.onreadystatechange=function(a){k||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||c(a)};return{setTimeoutCallback:function(a){h=!0;f=a;return this},setCallback:function(a){l=a;return this},setTimeoutLimit:function(a){g=a;return this},load:function(){n.parentNode.insertBefore(e,n);h&&d()}}}function g(a,b){p(a,b).load()}
function d(a,b){if(0===b.length)return!1;if(a===b.length){var c=(window.localStorage&&"true"===localStorage.janrainLocalWidgetCodeEnabled?localStorage.janrainLocalWidgetCodeUrl||"http://apps.janrain.com:4567/":"https:"===document.location.protocol?"https://d16s8pqtk4uodx.cloudfront.net/":"http://d16s8pqtk4uodx.cloudfront.net/")+"manifest-development/"+b.join("-")+".js?version="+encodeURIComponent("2014.WID.1.99.1_widgets_358");g(c)}else q(janrain.loadedPackages,b[a])?(r(b,a),d(a,b)):(janrain.loadedPackages.push(b[a]),
"login"===b[a]&&"en"===janrain.settings.language||"capture"===b[a]?d(a+1,b):g((window.localStorage&&"true"===localStorage.janrainLocalWidgetCodeEnabled?localStorage.janrainLocalWidgetCodeUrl||"http://apps.janrain.com:4567/":"https:"===document.location.protocol?"https://d29usylhdk1xyu.cloudfront.net/":"http://widget-cdn.rpxnow.com/")+"translations/"+b[a]+"/"+janrain.settings.language,function(){d(a+1,b)}))}function h(a){for(var b={},c=0,d=a.length;c<d;c++)b[a[c]]=a[c];return b}function r(a,b,c){c=
a.slice((c||b)+1||a.length);a.length=0>b?a.length+b:b;return a.push.apply(a,c)}function q(a,b){return h(a).hasOwnProperty(b)}"object"!==typeof window.janrain.engage&&(window.janrain.engage={});janrain.settings.capture||(janrain.settings.capture={});janrain.settings.common||(janrain.settings.common={});janrain.settings.language||(janrain.settings.language="en");janrain.settings.packages?janrain.settings.tokenUrl&&janrain.settings.packages.push("login"):janrain.settings.packages=["login"];janrain.settings.share||
(janrain.settings.share={});janrain.loadedPackages||(janrain.loadedPackages=[]);janrain.settings.linkClass||(janrain.settings.linkClass="janrainEngage");"undefined"===typeof janrain.settings.common.appUrl&&(janrain.settings.common.appUrl="https://oreilly-dev.rpxnow.com");"undefined"===typeof janrain.settings.showAttribution&&(janrain.settings.showAttribution=!1);"undefined"===typeof janrain.settings.type&&(janrain.settings.type="embed");"undefined"===typeof janrain.settings.format&&(janrain.settings.format=
"two column");"undefined"===typeof janrain.settings.width&&(janrain.settings.width="350");"undefined"===typeof janrain.settings.providersPerPage&&(janrain.settings.providersPerPage="4");janrain.settings.actionText||(janrain.settings.actionText="Sign in using your account with");"undefined"===typeof janrain.settings.fontColor&&(janrain.settings.fontColor="#333333");"undefined"===typeof janrain.settings.fontFamily&&(janrain.settings.fontFamily="arial");"undefined"===typeof janrain.settings.backgroundColor&&
(janrain.settings.backgroundColor="#FFFFFF");"undefined"===typeof janrain.settings.buttonBorderColor&&(janrain.settings.buttonBorderColor="#CCCCCC");"undefined"===typeof janrain.settings.buttonBorderRadius&&(janrain.settings.buttonBorderRadius="5");"undefined"===typeof janrain.settings.buttonBackgroundStyle&&(janrain.settings.buttonBackgroundStyle="gradient");"undefined"===typeof janrain.settings.borderWidth&&(janrain.settings.borderWidth="15");"undefined"===typeof janrain.settings.borderColor&&(janrain.settings.borderColor=
"#CCCCCC");"undefined"===typeof janrain.settings.borderRadius&&(janrain.settings.borderRadius="5");"undefined"===typeof janrain.settings.appId&&(janrain.settings.appId="lknnapkjbdbgnoahginn");"undefined"===typeof janrain.settings.appUrl&&(janrain.settings.appUrl="https://oreilly-dev.rpxnow.com");janrain.settings.permissions=["customizable_auth_widget_hide_attribution","customizable_auth_widget_styling"];"undefined"===typeof janrain.settings.providers&&(janrain.settings.providers=["linkedin","facebook",
"google","twitter"]);"undefined"===typeof janrain.settings.noReturnExperience&&(janrain.settings.noReturnExperience=!1);"undefined"===typeof janrain.settings.facebookAppId&&(janrain.settings.facebookAppId="492163520850226");"undefined"===typeof janrain.settings.maxProviders&&(janrain.settings.maxProviders="16");"undefined"===typeof janrain.settings.share.attributionDisplay&&(janrain.settings.share.attributionDisplay=!0);"undefined"===typeof janrain.settings.share.elementColor&&(janrain.settings.share.elementColor=
"#333333");"undefined"===typeof janrain.settings.share.elementHoverBackgroundColor&&(janrain.settings.share.elementHoverBackgroundColor="#eeeeee");"undefined"===typeof janrain.settings.share.elementButtonBorderRadius&&(janrain.settings.share.elementButtonBorderRadius="6");"undefined"===typeof janrain.settings.share.elementBorderColor&&(janrain.settings.share.elementBorderColor="#cccccc");"undefined"===typeof janrain.settings.share.elementBackgroundColor&&(janrain.settings.share.elementBackgroundColor=
"#f6f6f6");"undefined"===typeof janrain.settings.share.elementLinkColor&&(janrain.settings.share.elementLinkColor="#009DDC");"undefined"===typeof janrain.settings.share.elementBorderRadius&&(janrain.settings.share.elementBorderRadius="3");"undefined"===typeof janrain.settings.share.elementButtonBoxShadow&&(janrain.settings.share.elementButtonBoxShadow="3");"undefined"===typeof janrain.settings.share.modalOpacity&&(janrain.settings.share.modalOpacity="0.5");"undefined"===typeof janrain.settings.share.modalBorderRadius&&
(janrain.settings.share.modalBorderRadius="5");"undefined"===typeof janrain.settings.share.bodyColor&&(janrain.settings.share.bodyColor="#333333");"undefined"===typeof janrain.settings.share.bodyTabBackgroundColor&&(janrain.settings.share.bodyTabBackgroundColor="#f8f8f8");"undefined"===typeof janrain.settings.share.bodyTabColor&&(janrain.settings.share.bodyTabColor="#000000");"undefined"===typeof janrain.settings.share.bodyContentBackgroundColor&&(janrain.settings.share.bodyContentBackgroundColor=
"#ffffff");"undefined"===typeof janrain.settings.share.bodyBackgroundColorOverride&&(janrain.settings.share.bodyBackgroundColorOverride=!1);"undefined"===typeof janrain.settings.share.bodyFontFamily&&(janrain.settings.share.bodyFontFamily="Helvetica");"undefined"===typeof janrain.settings.share.bodyBackgroundColor&&(janrain.settings.share.bodyBackgroundColor="#009DDC");"undefined"===typeof janrain.settings.share.modalBackgroundColor&&(janrain.settings.share.modalBackgroundColor="#000000");"undefined"===
typeof janrain.settings.share.appUrl&&(janrain.settings.share.appUrl="https://oreilly-dev.rpxnow.com");janrain.settings.share.permissions=["customizable_share_widget_hide_attribution","customizable_share_widget_styling","customizable_share_widget_contact_mode","customizable_share_widget_email_mode"];"undefined"===typeof janrain.settings.share.providers&&(janrain.settings.share.providers=[]);"undefined"===typeof janrain.settings.share.providersEmail&&(janrain.settings.share.providersEmail=[]);"undefined"===
typeof janrain.settings.share.modes&&(janrain.settings.share.modes=["broadcast"]);janrain.settings.packages=function(a){a=h(a);var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b}(janrain.settings.packages);janrain.settings.packages.sort();d(0,janrain.settings.packages)})();
